# Service - LoadBalancer
# # pb-service -lb.yml
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic-app
spec:
  selector:
    app: petclinic-app
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 32750
    protocol: TCP
